name: Build PyInstaller Executable

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.8']
        architecture: ['x64', 'x86']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        pip install pyinstaller pandas==1.2.5 numpy==1.19.5 reportlab pyqt5 fpdf
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --add-data "logo.png:." --hidden-import "pandas._libs.tslibs.np_datetime" --hidden-import "pandas._libs.tslibs.np_timedelta" --hidden-import "reportlab" --hidden-import "PyQt5" main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable-${{ matrix.architecture }}
        path: dist/main.exe
